# Travis optimizations, see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
cache:
  directories:
  - node_modules
install: npm update

language: node_js

node_js:
- '0.10'
- '0.12'
- iojs
